export const ADD = 'ADD'
export const MINUS = 'MINUS'
export const USERDATA = 'USERDATA'
export const LOCATION = 'LOCATION'
export const RECENTSHOP = 'RECENTSHOP'
export const SELECTSHOPLOCATION = 'SELECTSHOPLOCATION'
